version: "3.8"

services:
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    depends_on:
      - server
    volumes:
      - ./client:/client
      - ./client/node_modules:/client/node_modules
    command: ["yarn", "start"]
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 3000:3000

  server:
    build:
      context: ./
      dockerfile: ./server/Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./server:/server
      - ./server/node_modules:/server/node_modules
    command: ["yarn", "start"]
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    env_file:
      - ./server/.env

  postgres:
    container_name: postgres
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat-db

volumes:
  postgres_data: {}
