version: "3.8"

services:
  client:
    build:
      context: ./
      dockerfile: ./client/Dockerfile
    volumes:
      - ./client:/client
      - ./client/node_modules:/client/node_modules
    command: sh -c "npm rebuild node-sass && npm run start"
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
